# debug : true

spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parents_day?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: boram0415@bkwinners.com
    password: 90skffl0!!



server:
  port: 8070
  error:
    whitelabel:
      enabled: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.day.parents.parentsday.model